name: flutter_nfc_plugin
description: Flutter NFC plugin project. Allowing to start you app within an NFC tag.
version: 0.0.6
homepage: https://github.com/dukhanov/flutter-nfc-plugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: it.dukhanov.flutter.nfc_plugin
    pluginClass: NfcPlugin